name = "gorrion"
version = "0.1.0"
target = "erlang"
description = "Ecto-like database migration library for Gleam + PostgreSQL"
licences = ["MIT"]
repository = { type = "github", user = "davecaos", repo = "gorrion" }

links = [
  { title = "GitHub", href = "https://github.com/davecaos/gorrion" }
]

[dependencies]
gleam_stdlib = ">= 0.51.0"
pog = ">= 4.1.0"
simplifile = ">= 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
