name = "gorrion"
version = "0.1.0"
target = "erlang"
description = "Ecto-like driver-agnostic database migration library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "davecaos", repo = "gorrion" }

links = [
  { title = "GitHub", href = "https://github.com/davecaos/gorrion" }
]

[dependencies]
gleam_stdlib = ">= 0.71.0"
common_sql = ">= 1.0.0"
simplifile = ">= 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
common_sql_sqlite = ">= 1.0.2 and < 2.0.0"
sqlight = ">= 1.0.3 and < 2.0.0"
